import Head from 'next/head';
import Header from '@/components/Header';
import React from 'react';

import Image from 'next/image';

const Aboutme = () => {
  return (
    <div>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <p className='text-[rgb(251,247,245)] text-2xl font-semibold text-center
       decoration-[#00AFF0] underline pt-5 pb-10'>About Us</p>

      <div className='flex flex-col items-center justify-center'>
        <Image src="/pngaaa.com-4993052.png" alt='' height={200} width={200} />
        <p className='text-[rgb(251,247,245)] text-lg font-semibold text-center
       py-5 px-12 md:px-24'>"At Mainland Media Group, we specialize
          in bringing your brand to life. From custom websites and
          eye-catching logos to impactful promotional materials,
          we provide creative solutions that help your business
          stand out. Our passion is helping businesses succeed
          through innovative design and thoughtful branding,
          tailored to meet your unique vision and goals."
        </p>
      </div>
    </div>
  );
}

export default Aboutme;
